ToDoListApp/ToDoListApp/Models/ListMain.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

    namespace ToDoListApp.Models
{
    public class ListMain
    {

        [Key]
        public int Id { get; set; }


        public string? UserName { get; set; }

        [Required(ErrorMessage = "Please Enter Name of the List")]
        public string ListName { get; set; }


    }
}

ToDoListApp/ToDoListApp/Controllers/ListMainController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using ToDoListApp.Data;
using ToDoListApp.Models;


namespace ToDoListApp.Controllers
{
    //This controller manages the main list names and who they are saved to, not the detail of the lists.
    public class ListMainController : Controller
    {
        private readonly ApplicationDBContext main_db;

        public ListMainController(ApplicationDBContext db)
        {
            main_db = db;
        }

        // GET: ListMainController
        public IActionResult Index()
        {
            IEnumerable<ListMain> objToDoList = main_db.ListM;

            return View(objToDoList);
        }


        public IActionResult AddNewList()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddNewList(ListMain obj)
        {
            if (User.Identity.IsAuthenticated)
            {
                //Testing
                obj.UserName = User.Identity.Name;
            }
            else
            {
                obj.UserName = "Guest";
            }

            if (ModelState.IsValid)
            {
                main_db.ListM.Add(obj);
                main_db.SaveChanges();
                return RedirectToAction("Index", new RouteValueDictionary(new { controller = "ToDoList", action = "Index", currentL = obj.ListName }));
            }

            return View();
        }

        public IActionResult Edit(int? id, string currentListName)
        {
            TempData["CurrentListName"] = currentListName;

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var taskFromDb = main_db.ListM.Find(id);


            if (taskFromDb == null)
            {
                return NotFound();
            }

            return View(taskFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ListMain obj, string currentListName)
        {
            TempData["CurrentListName"] = currentListName;
            ////Asign owner of list
            if (User.Identity.IsAuthenticated)
            {
                obj.UserName = User.Identity.Name;
            }
            else
            {
                obj.UserName = "Guest";
            }

            if (ModelState.IsValid)
            {
                main_db.ListM.Update(obj);
                main_db.SaveChanges();

                return RedirectToAction("UpdateListName", new RouteValueDictionary(new { controller = "ToDoList", action = "UpdateListName", newListName = obj.ListName, currentListName = currentListName }));
            }

            return View();

        }

        public IActionResult LoadTemplate()
        {

            List<string> templates = new List<string>();

            string[] tempList = Directory.GetFiles("wwwroot/Templates");

            foreach(string str in tempList)
            {
                templates.Add(str);
            }
            

            //Checking if user is signed in, then if they have any custom templates
            if(User.Identity.IsAuthenticated)
            {
                if (Directory.Exists("wwwroot/Templates/" + User.Identity.Name))
                {
                    string[] userTemplates = Directory.GetFiles("wwwroot/Templates/" + User.Identity.Name);

                    foreach(string str in userTemplates)
                    {
                        templates.Add(str);
                    }
               
                }
                
            }

            List<ListMain> files = new List<ListMain>();

            //Renaming read files to remove .txt and adding them to a list to return
            foreach (string filePath in templates)
            {
                string fileWithoutTxt = filePath;
                fileWithoutTxt = fileWithoutTxt.Replace(".txt", "");
                files.Add(new ListMain { ListName = Path.GetFileName(fileWithoutTxt) });
            }

            return View(files);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LoadTemplate(string templateName)
        {
            return View();
        }

        public IActionResult SaveTemplate(string templateName)
        {
            TempData["TemplateName"] = templateName;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveTemplate(string templateName, string listName) 
        {
            ListMain listMain = new ListMain();

            if(User.Identity.IsAuthenticated)
            {
                listMain.UserName = User.Identity.Name;
            }
            else
            {
                listMain.UserName = "Template";
            }
            listMain.ListName = listName;


            main_db.ListM.Add(listMain);
            main_db.SaveChanges();

            return RedirectToAction("SaveTemplate", new RouteValueDictionary(new { controller = "ToDoList", action = "SaveTemplate", templateName = templateName, listName = listName  }));
        }

        public async Task<IActionResult> DeleteList(string listName)
        {

            var listToDelete = await main_db.ListM.AsNoTracking().Where(x => x.ListName == listName).FirstOrDefaultAsync();

            if(listToDelete == null)
            {
                return View("Error");
            }

            main_db.ListM.Remove(listToDelete);
            main_db.SaveChanges();

            return RedirectToAction("DeleteList", new RouteValueDictionary(new { controller = "ToDoList", action = "DeleteList", listName = listName }));
        }

        public IActionResult SaveAsTemplate(string templateName)
        {
            TempData["TemplateName"] = templateName;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveAsTemplate(ListMain obj, string templateName)
        {
            return RedirectToAction("SaveAsTemplate", new RouteValueDictionary(new { controller = "ToDoList", action = "SaveAsTemplate", listName = obj.ListName, templateName = templateName }));
        }

    }
}

ToDoListApp/ToDoListApp/Views/ListMain/AddNewList.cshtml
@model ListMain

<h1 style="text-align:center"> Create a New List</h1>

<form method="Post" asp-action="AddNewList">
    <div class="border p-3 mt-4">
        
        @if(User.Identity.IsAuthenticated)
        {
            <div class="row pb-2">
                <h2 class="text-primary"> Name of the new list: </h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="ListName"></label>
                <input asp-for="ListName" class="form-control" />
                <span asp-validation-for="ListName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success" style="width:150px"> Create New List </button>
        
        }
        else
        {
            <h3 style="text-align:center"> You're not currently signed in. Sign in to save your own lists or use the public list below.</h3>
            <br />
            <div class="wrapper">
                <a asp-controller="ToDoList" asp-action="Index" asp-route-currentL="Guest List" type="button" style="width:500px" class="btn btn-success">
                    Create a Temporary List
                </a>
            </div>
        }
        

    </div>
</form>

ToDoListApp/ToDoListApp/Views/ListMain/Delete.cshtml
@model ToDoList
@{
    ViewData["Title"] = "Delete Task";
}

<form method="Post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class ="row pb-2">
            <h2 class="text-danger"> Delete Task</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Task"></label>
            <input asp-for="Task" class="form-control" />
            <span asp-validation-for="Task" class="text-danger"></span>
        </div>
        <button type="submit" class ="btn btn-success" style ="width:175px"> Delete This Task </button>


        <a asp-controller="ToDoList" asp-action="Index" class="btn btn-warning" style="width:150px">
        Back to List
        </a>
    </div>
</form>

ToDoListApp/ToDoListApp/Views/ListMain/Edit.cshtml
@model ListMain
@{
    ViewData["Title"] = "Edit List Name";
}

<form method="Post" asp-action="Edit" asp-route-currentListName="@TempData["CurrentListName"]">
    <div class="border p-3 mt-4">
        <div class ="row pb-2">
            <h2 class="text-primary"> Update List Name </h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="ListName"></label>
            <input asp-for="ListName" class="form-control" />
            <span asp-validation-for="ListName" class="text-danger"></span>
        </div>
        <button type="submit" class ="btn btn-success" style ="width:150px"> Update List Name </button>

        <a asp-controller="ListMain" asp-action="Index" class="btn btn-warning" style="width:150px">
        Back to Lists
        </a>
    </div>
</form>

ToDoListApp/ToDoListApp/Views/ListMain/Index.cshtml
@model IEnumerable<ListMain>
@{
    ViewData["Title"] = "Index";
}

@if (User.Identity.IsAuthenticated)
{
    <h1 style="text-align:center"> Welcome, @User.Identity.Name. These are your saved lists.</h1>
}
else
{
    <h1 style="text-align:center">Please sign in or use the public list</h1>
}


<br />



<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col" style="text-align:center; width:350px">Available Lists</th>
      <th scope="col" style="text-align:center; width:100px">Edit List</th>
    </tr>
  </thead>

  <tbody>
     @*going through each row of data*@

     @{bool UserHasLists = false;
     
      @foreach(var obj in Model)
            {
            <tr style="text-align:center">
                @if (User.Identity.IsAuthenticated)
                {
                    @if (obj.UserName == User.Identity.Name)
                    {
                        <td>
                            <div class="w-50 btn-group" role="group">
                                
                                <a asp-controller="ToDoList" asp-action="Index" asp-route-currentL="@obj.ListName" class="btn btn-success"> 
                                @obj.ListName</a>
                            </div>
                        </td>

                        <td style="text-align:center">
                            <div class="w-500 btn-group" role="group">
                                <a asp-controller="ListMain" asp-action="Edit" asp-route-id="@obj.Id" asp-route-currentListName="@obj.ListName" class="btn btn-warning"> <i class="bi bi-pencil-square"></i> </a>
                            </div>
                        </td>
                        UserHasLists = true;
                    }
                }
                else
                {
                        <td>
                            <div class="wrapper">
                                <a asp-controller="ToDoList" asp-action="Index" asp-route-currentL="Guest List" style="width:400px " class="btn btn-success">
                                    View the public list
                                </a>
                            </div>
                        </td>
                    break;
                }                                   
                   
                </tr>                   
            
            }
            }
  </tbody>

</table>

<div class="container p-1">
    <a asp-controller="ListMain" asp-action="LoadTemplate" class="btn btn-info" style="width:300px">
        Load List from a Template
    </a>

    @if (!UserHasLists)
    {
        <a asp-controller="ListMain" asp-action="AddNewList" class="btn btn-info" style="width:300px">
            Create Your First List
        </a>
    }

</div>

ToDoListApp/ToDoListApp/Views/ListMain/LoadTemplate.cshtml
@model IEnumerable<ListMain>
@{
    ViewData["Title"] = "Load New Template";
}


<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col" style="text-align:center; width:350px">Available Lists</th>
        </tr>
    </thead>

    <tbody>
        @*going through each row of data*@

        @{
            @foreach (var obj in Model)
            {
                <tr style="text-align:center">
                    
                            <td>
                                <div class="w-50 btn-group" role="group">

                                    <a asp-controller="ToDoList" asp-action="LoadTemplate" asp-route-templateName="@obj.ListName" class="btn btn-success">
                                        @obj.ListName
                                    </a>
                                </div>
                            </td>

                </tr>

            }
        }
    </tbody>

</table>

ToDoListApp/ToDoListApp/Views/ListMain/SaveAsTemplate.cshtml
@model ListMain

@{string templateName = TempData["TemplateName"].ToString();}


<h1 style="text-align:center"> New Template</h1>

<form method="Post" asp-action="SaveAsTemplate" asp-route-templateName="@templateName">
    <div class="border p-3 mt-4">

        @if (User.Identity.IsAuthenticated)
        {
            <div class="row pb-2">
                <h2 class="text-primary"> Name of the new template: </h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="ListName"></label>
                <input asp-for="ListName" class="form-control" />
                <span asp-validation-for="ListName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success" style="width:150px"> Save Template </button>

        }



    </div>
</form>

ToDoListApp/ToDoListApp/Views/ListMain/SaveTemplate.cshtml
@model ListMain

@{
    string currentTemplateName = @TempData["TemplateName"].ToString();
}

<h1 style="text-align:center"> Create a New List</h1>

<form method="Post" asp-action="SaveTemplate" asp-route-templateName="@currentTemplateName">
    <div class="border p-3 mt-4">

            <div class="row pb-2">
                <h2 class="text-primary"> Enter the name to save the template as: </h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="ListName"></label>
                <input asp-for="ListName" class="form-control" />
                <span asp-validation-for="ListName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success" style="width:150px"> Save Template </button>

    </div>
</form>